/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BxBuddiezRouteImport } from './routes/bx-buddiez'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as RatingsIndexRouteImport } from './routes/ratings.index'
import { Route as RatingsSlugRouteImport } from './routes/ratings.$slug'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as WritersSlugRouteImport } from './routes/writers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BxBuddiezRoute = BxBuddiezRouteImport.update({
  id: '/bx-buddiez',
  path: '/bx-buddiez',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsIndexRoute = RatingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RatingsRoute,
} as any)
const RatingsSlugRoute = RatingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RatingsRoute,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsRoute,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewsRoute,
} as any)
const WritersSlugRoute = WritersSlugRouteImport.update({
  id: '/writers/$slug',
  path: '/writers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bx-buddiez': typeof BxBuddiezRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/editorial': typeof EditorialRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/search': typeof SearchRoute
  '/sponsorship': typeof SponsorshipRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/ratings/': typeof RatingsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bx-buddiez': typeof BxBuddiezRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/editorial': typeof EditorialRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sponsorship': typeof SponsorshipRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/ratings': typeof RatingsIndexRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bx-buddiez': typeof BxBuddiezRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/editorial': typeof EditorialRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/search': typeof SearchRoute
  '/sponsorship': typeof SponsorshipRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/ratings/': typeof RatingsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bx-buddiez'
    | '/contact'
    | '/delivery'
    | '/editorial'
    | '/news'
    | '/privacy'
    | '/ratings'
    | '/reviews'
    | '/search'
    | '/sponsorship'
    | '/articles/$slug'
    | '/ratings/$slug'
    | '/reviews/$slug'
    | '/writers/$slug'
    | '/ratings/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bx-buddiez'
    | '/contact'
    | '/delivery'
    | '/editorial'
    | '/news'
    | '/privacy'
    | '/search'
    | '/sponsorship'
    | '/articles/$slug'
    | '/ratings/$slug'
    | '/reviews/$slug'
    | '/writers/$slug'
    | '/ratings'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bx-buddiez'
    | '/contact'
    | '/delivery'
    | '/editorial'
    | '/news'
    | '/privacy'
    | '/ratings'
    | '/reviews'
    | '/search'
    | '/sponsorship'
    | '/articles/$slug'
    | '/ratings/$slug'
    | '/reviews/$slug'
    | '/writers/$slug'
    | '/ratings/'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BxBuddiezRoute: typeof BxBuddiezRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  EditorialRoute: typeof EditorialRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  RatingsRoute: typeof RatingsRouteWithChildren
  ReviewsRoute: typeof ReviewsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SponsorshipRoute: typeof SponsorshipRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  WritersSlugRoute: typeof WritersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bx-buddiez': {
      id: '/bx-buddiez'
      path: '/bx-buddiez'
      fullPath: '/bx-buddiez'
      preLoaderRoute: typeof BxBuddiezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings/': {
      id: '/ratings/'
      path: '/'
      fullPath: '/ratings/'
      preLoaderRoute: typeof RatingsIndexRouteImport
      parentRoute: typeof RatingsRoute
    }
    '/ratings/$slug': {
      id: '/ratings/$slug'
      path: '/$slug'
      fullPath: '/ratings/$slug'
      preLoaderRoute: typeof RatingsSlugRouteImport
      parentRoute: typeof RatingsRoute
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/writers/$slug': {
      id: '/writers/$slug'
      path: '/writers/$slug'
      fullPath: '/writers/$slug'
      preLoaderRoute: typeof WritersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RatingsRouteChildren {
  RatingsSlugRoute: typeof RatingsSlugRoute
  RatingsIndexRoute: typeof RatingsIndexRoute
}

const RatingsRouteChildren: RatingsRouteChildren = {
  RatingsSlugRoute: RatingsSlugRoute,
  RatingsIndexRoute: RatingsIndexRoute,
}

const RatingsRouteWithChildren =
  RatingsRoute._addFileChildren(RatingsRouteChildren)

interface ReviewsRouteChildren {
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsSlugRoute: ReviewsSlugRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BxBuddiezRoute: BxBuddiezRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  EditorialRoute: EditorialRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  RatingsRoute: RatingsRouteWithChildren,
  ReviewsRoute: ReviewsRouteWithChildren,
  SearchRoute: SearchRoute,
  SponsorshipRoute: SponsorshipRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  WritersSlugRoute: WritersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
